AllCops:
  Exclude:
    - bin/*
Documentation:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10  
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Max: 100